import tmx
import sys
import os

def create_mapdata(fileName):
    allLines="""
; -----------------------------------------------------------------------------
; MAPDATAO CONTAINS THE MAP. IT IS A MATRIX OF 64X64 STORED ROW BY ROW. A VALUE
; OF 0 MEANS FREE. 1 MEANS RED BLOCK. 2 MEANS GREEN BLOCK AND 3 MEANS BLUE
; BLOCK. THIS DATA HAS BEEN GENERATED BY CREATE_MAP.PY FROM A TILED FILE.
; -----------------------------------------------------------------------------\n
"""[1:]
    curLine='MAPDATAO    DC.B    '
    tmxMap=tmx.TileMap.load(fileName)
    numRows=tmxMap.height
    numCols=tmxMap.width
    playerPosX=-1
    playerPosY=-1
    numTreasures=0
    if (numRows!=64 or numCols!=64):
        sys.exit('[ERROR] THE MAP MUST BE 64X64')
    for rowIndex in range(numRows):
        for colIndex in range(numCols):
            curValue=tmxMap.layers[0].tiles[colIndex+rowIndex*numCols].gid-1
            if curValue==4:
                if playerPosX!=-1:
                    sys.exit('[ERROR] ONLY ONE PLAYER CAN BE IN THE MAP.')
                playerPosX=colIndex*256+128
                playerPosY=rowIndex*256+128
                curValue=0
            if curValue==2:
                numTreasures+=1
            curString='$'+format(curValue,'02X')+','
            if (len(curLine)+len(curString))<80:
                curLine+=curString
            else:
                allLines+=(curLine[:-1]+'\n')
                curLine='            DC.B    '+curString
    allLines+=(curLine[:-1]+'\n\n')
    if playerPosX==-1 | playerPosY==-1:
        sys.exit('[ERROR] PLAYER MUST BE IN THE MAP.')

    newComment="""
; -----------------------------------------------------------------------------
; MAPPLRIX AND MAPPLRIY CONTAIN THE INITIAL POSITION OF THE PLAYER.
; THIS COULD BE OPTIMIZED BY DEFINING THEM AS EQU INSTEAD OF DC.W SO THAT THEY
; DO NOT OCCUPY 68000 MEMORY.
; -----------------------------------------------------------------------------\n
"""[1:]
    allLines+=newComment
    allLines+='MAPPLRIX    DC.W    '+'$'+format(playerPosX,'04X')+'\n'
    allLines+='MAPPLRIY    DC.W    '+'$'+format(playerPosY,'04X')+'\n\n'


    if numTreasures==0:
        sys.exit('[ERROR] THE MAP MUST CONTAIN AT LEAST ONE TREASURE')

    newComment="""
; -----------------------------------------------------------------------------
; MAPNUMTR CONTAINS THE NUMBER OF TREASURES IN THE MAP. THIS COULD BE OPTIMIZED
; SIMILARLY TO MAPPLRIX AND MAPPLRIY.
; -----------------------------------------------------------------------------\n
"""[1:]
    allLines+=newComment
    allLines+='MAPNUMTR    DC.W    '+'$'+format(numTreasures,'04X')+'\n'

    return allLines

def create_map(fileName,outPath):
    mapdataLines=create_mapdata(fileName)
    baseName=os.path.join(outPath,os.path.splitext(os.path.basename(fileName))[0])
    with open(baseName+'.X68','w') as outFile:
        outFile.write(mapdataLines)

create_map('../RES/MAPDATA.TMX','../DATA/')
